### ISSUE TITLE
New equation crashes SessionVisualizer 

### ISSUE THREAD

**Issue by jerryepratt** [ihmcrobotics/simulation-construction-set-2#133]
If you create an equation and plot the variable. Then close the SessionVisualizer. Then reload the data, it crashes.

**Comment by jerryepratt** [comment]
Here is a YoEquation.scs2.yoEquation that give a problem:

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<YoEquations>
    <yoEquations name="NewEquation">
        <aliases>
            <name>a</name>
            <value>
                <constant>false</constant>
                <yoVariableValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="yoDoubleDefinition" description="" name="foo" namespace="root.userRegistry">
                    <lowerBound>0.0</lowerBound>
                    <upperBound>1.0</upperBound>
                </yoVariableValue>
            </value>
        </aliases>
        <equation>a = b + c</equation>
    </yoEquations>
</YoEquations>


`Here's the exception that gets thrown:

java.lang.RuntimeException: Failed to build the equation: a = b + c, missing inputs: [b, c]
	at us.ihmc.scs2.symbolic.Equation.checkBuildStatus(Equation.java:184)
	at us.ihmc.scs2.symbolic.Equation.reset(Equation.java:169)
	at us.ihmc.scs2.symbolic.YoEquationManager.reset(YoEquationManager.java:167)
	at us.ihmc.scs2.session.Session.initializeRunTick(Session.java:1696)
	at us.ihmc.scs2.session.Session.runTick(Session.java:1645)
	at us.ihmc.scs2.session.Session$PeriodicTaskWrapper.singleExecuteAndSleep(Session.java:2669)
	at us.ihmc.scs2.session.Session$PeriodicTaskWrapper.run(Session.java:2653)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

If I delete the yoEquation file, then things work again.

**Comment by jerryepratt** [comment]
> <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<YoEquations>
    <yoEquations name="NewEquation">
        <aliases>
            <name>a</name>
            <value>
                <constant>false</constant>
                <yoVariableValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="yoDoubleDefinition" description="" name="foo" namespace="root.userRegistry">
                    <lowerBound>0.0</lowerBound>
                    <upperBound>1.0</upperBound>
                </yoVariableValue>
            </value>
        </aliases>
        <equation>a = b + c</equation>
    </yoEquations>
</YoEquations>

**Comment by jerryepratt** [comment]
![image](https://github.com/ihmcrobotics/simulation-construction-set-2/assets/110582920/ac40c161-fa59-470d-89bb-0ef240926894)
