### ISSUE TITLE
Resizing buffer on the fly causes ArrayOutOfBoundsException

### ISSUE THREAD

**Issue by SylvainBertrand** [ihmcrobotics/simulation-construction-set-2#32]

**Comment by SylvainBertrand** [comment]
Got the size increase bug fixed, but downsizing still outputs some exception at runtime:
```Java HotSpot(TM) 64-Bit Server VM warning: Option CreateMinidumpOnCrash was deprecated in version 9.0 and will likely be removed in a future release. Use option CreateCoredumpOnCrash instead.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jfoenix.adapters.ReflectionHelper (file:/C:/Users/nadiaocu/.gradle/caches/modules-2/files-2.1/com.jfoenix/jfoenix/9.0.10/a7625792db8d15615ea6eebbc31e01504f20b2df/jfoenix-9.0.10.jar) to method java.lang.reflect.AccessibleObject.setAccessible0(boolean)
WARNING: Please consider reporting this to the maintainers of com.jfoenix.adapters.ReflectionHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
210317 15:11:21:872 [INFO] (YoVariableClientImplementation.java:87): Requesting handshake from nuc
[m210317 15:11:22:251 [INFO] (YoVariableClientImplementation.java:99): Requesting model file from nadia
[m210317 15:11:22:253 [INFO] (YoVariableClientImplementation.java:105): Requesting resource bundle
[m210317 15:11:22:903 [INFO] (YoVariableClientImplementation.java:108): Received model
[m210317 15:11:23:745 [INFO] (YoManager.java:45): Linking YoVariables
[m210317 15:11:24:143 [INFO] (YoManager.java:57): UI linked YoVariables created
[m210317 15:11:24:147 [INFO] (YoRobotFX.java:54): Loading robot: nadia
[m210317 15:11:24:163 [INFO] (YoRobotFX.java:62): Loaded robot: nadia
[m210317 15:11:24:170 [INFO] (YoCompositeSearchManager.java:157): Searching default YoComposite.
[m210317 15:11:24:435 [INFO] (YoCompositeSearchManager.java:159): Initialized default YoComposite.
[m210317 15:11:24:436 [INFO] (Session.java:203): Starting session
[m210317 15:11:24:436 [INFO] (Session.java:216): Started session's thread
[m210317 15:11:24:450 [INFO] (YoCompositeSearchManager.java:263): Loading file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\YoComposite.scs2.yoComposite
[m210317 15:11:24:455 [INFO] (YoGraphicFXManager.java:115): Loading file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\YoGraphics.scs2.yoGraphic
[m210317 15:11:24:469 [INFO] (YoEntryTabPaneController.java:264): Loading from file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\YoEntry.scs2.yoEntry
[m210317 15:11:24:488 [INFO] (YoChartGroupPanelController.java:546): Loading file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\MainYoChartGroup.scs2.chart
[m210317 15:11:25:758 [INFO] (YoChartGroupPanelController.java:546): Loading file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\SecondaryYoChartGroup0.scs2.chart
[m210317 15:11:25:894 [INFO] (YoChartGroupPanelController.java:546): Loading file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\SecondaryYoChartGroup1.scs2.chart
[m210317 15:11:26:025 [INFO] (YoChartGroupPanelController.java:546): Loading file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\SecondaryYoChartGroup2.scs2.chart
[m210317 15:11:26:082 [INFO] (YoChartGroupPanelController.java:546): Loading file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\SecondaryYoChartGroup3.scs2.chart
[m210317 15:11:26:149 [INFO] (YoChartGroupPanelController.java:546): Loading file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\SecondaryYoChartGroup4.scs2.chart
[m210317 15:11:26:221 [INFO] (YoChartGroupPanelController.java:546): Loading file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\SecondaryYoChartGroup5.scs2.chart
[m210317 15:11:26:315 [INFO] (YoChartGroupPanelController.java:546): Loading file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\SecondaryYoChartGroup6.scs2.chart
[mException in thread "Thread-4" java.lang.IndexOutOfBoundsException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
	at us.ihmc.scs2.sharedMemory.YoSharedBuffer.prepareLinkedBuffersForPull(YoSharedBuffer.java:320)
	at us.ihmc.scs2.session.Session.finalizeRunTick(Session.java:351)
	at us.ihmc.scs2.sessionVisualizer.jfx.session.remote.RemoteSession.finalizeRunTick(RemoteSession.java:130)
	at us.ihmc.scs2.session.Session.runTick(Session.java:322)
	at us.ihmc.scs2.sessionVisualizer.jfx.session.remote.RemoteSession.receivedTimestampAndData(RemoteSession.java:90)
	at us.ihmc.scs2.sessionVisualizer.jfx.session.remote.RemoteSessionFactory.receivedTimestampAndData(RemoteSessionFactory.java:32)
	at us.ihmc.robotDataLogger.YoVariableClientImplementation.receivedTimestampAndData(YoVariableClientImplementation.java:182)
	at us.ihmc.robotDataLogger.dataBuffers.RegistryConsumer.handlePackets(RegistryConsumer.java:155)
	at us.ihmc.robotDataLogger.dataBuffers.RegistryConsumer.run(RegistryConsumer.java:67)
Caused by: java.lang.IndexOutOfBoundsException: from is out-of-bound, should be in [0, 8192[, but was: 9986
	at us.ihmc.scs2.sharedMemory.tools.BufferTools.computeSubLength(BufferTools.java:40)
	at us.ihmc.scs2.sharedMemory.LinkedYoVariable.consumeBufferSampleRequest(LinkedYoVariable.java:124)
	at us.ihmc.scs2.sharedMemory.LinkedYoVariable.prepareForPull(LinkedYoVariable.java:99)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[1;31m210317 15:13:03:560 [ERROR] (io.netty.util.concurrent.DefaultPromise.rejectedExecution): Failed to submit a listener notification task. Event loop shut down?
[m java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:867) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:778) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:768) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:112) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:89) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:1017) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:610) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:465) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:1003) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:242) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at us.ihmc.robotDataLogger.websocket.client.discovery.HTTPDataServerConnection.close(HTTPDataServerConnection.java:276) ~[ihmc-robot-data-logger-0.20.7.jar:0.20.7]
	at us.ihmc.robotDataLogger.websocket.client.discovery.DataServerDiscoveryClient.close(DataServerDiscoveryClient.java:123) ~[ihmc-robot-data-logger-0.20.7.jar:0.20.7]
	at us.ihmc.robotDataLogger.websocket.client.discovery.DataServerDiscoveryClient.close(DataServerDiscoveryClient.java:108) ~[ihmc-robot-data-logger-0.20.7.jar:0.20.7]
	at us.ihmc.scs2.sessionVisualizer.jfx.session.remote.RemoteSessionManagerController.shutdown(RemoteSessionManagerController.java:373) ~[main/:?]
	at us.ihmc.scs2.sessionVisualizer.jfx.session.remote.RemoteSessionManagerController.lambda$21(RemoteSessionManagerController.java:258) ~[main/:?]
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247) ~[javafx-base-15.0.1-win.jar:?]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80) ~[javafx-base-15.0.1-win.jar:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234) ~[javafx-base-15.0.1-win.jar:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[javafx-base-15.0.1-win.jar:?]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[javafx-base-15.0.1-win.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[javafx-base-15.0.1-win.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[javafx-base-15.0.1-win.jar:?]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[javafx-base-15.0.1-win.jar:?]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) ~[javafx-base-15.0.1-win.jar:?]
	at javafx.event.Event.fireEvent(Event.java:198) ~[javafx-base-15.0.1-win.jar:?]
	at com.sun.javafx.stage.WindowPeerListener.closing(WindowPeerListener.java:93) ~[javafx-graphics-15.0.1-win.jar:?]
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:147) ~[javafx-graphics-15.0.1-win.jar:?]
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40) ~[javafx-graphics-15.0.1-win.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:391) ~[?:?]
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$4(GlassWindowEventHandler.java:176) ~[javafx-graphics-15.0.1-win.jar:?]
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412) ~[javafx-graphics-15.0.1-win.jar:?]
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:174) ~[javafx-graphics-15.0.1-win.jar:?]
	at com.sun.glass.ui.Window.handleWindowEvent(Window.java:1351) ~[javafx-graphics-15.0.1-win.jar:?]
	at com.sun.glass.ui.Window.notifyClose(Window.java:1251) ~[javafx-graphics-15.0.1-win.jar:?]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[javafx-graphics-15.0.1-win.jar:?]
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174) ~[javafx-graphics-15.0.1-win.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
210317 15:13:03:567 [INFO] (SessionVisualizer.java:103): Simulation GUI is going down.
[m210317 15:13:03:568 [INFO] (YoGraphicFXManager.java:141): Saving file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\YoGraphics.scs2.yoGraphic
[m210317 15:13:03:583 [INFO] (YoCompositeSearchManager.java:282): Saving file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\YoComposite.scs2.yoComposite
[m210317 15:13:03:586 [INFO] (YoEntryTabPaneController.java:235): Saving to file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\YoEntry.scs2.yoEntry
[m210317 15:13:03:591 [INFO] (YoChartGroupPanelController.java:568): Saving file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\MainYoChartGroup.scs2.chart
[m210317 15:13:03:595 [INFO] (YoChartGroupPanelController.java:568): Saving file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\SecondaryYoChartGroup0.scs2.chart
[m210317 15:13:03:598 [INFO] (YoChartGroupPanelController.java:568): Saving file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\SecondaryYoChartGroup1.scs2.chart
[m210317 15:13:03:601 [INFO] (YoChartGroupPanelController.java:568): Saving file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\SecondaryYoChartGroup2.scs2.chart
[m210317 15:13:03:604 [INFO] (YoChartGroupPanelController.java:568): Saving file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\SecondaryYoChartGroup3.scs2.chart
[m210317 15:13:03:608 [INFO] (YoChartGroupPanelController.java:568): Saving file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\SecondaryYoChartGroup4.scs2.chart
[m210317 15:13:03:611 [INFO] (YoChartGroupPanelController.java:568): Saving file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\SecondaryYoChartGroup5.scs2.chart
[m210317 15:13:03:614 [INFO] (YoChartGroupPanelController.java:568): Saving file: C:\Users\nadiaocu\SCS2\Configurations\nadia\NadiaControllerFactory\SecondaryYoChartGroup6.scs2.chart
[m210317 15:13:03:686 [INFO] (Session.java:234): Stopped session's thread
[m```

**Comment by SylvainBertrand** [comment]
Should be fixed
